### ISSUE TITLE
Set MIDI Input buffer size in Windows

### ISSUE THREAD

**Issue by lozjackson** [Julusian/node-midi#15]
We would like to use this library, however we have a specific requirement to be able to send large MIDI message packets up to 16384 bytes in size.

I can see there is an option to set the buffer size in RT MIDI here: https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L864

The buffer size is currently limited to 2048 here: https://github.com/Julusian/node-midi/blob/master/src/input.cpp#L48

Is there any easy way to override that from our app when consuming node-midi?.. if thats not currently possible would you be willing to add an option to configure it?

**Comment by lozjackson** [comment]
@Julusian I've opened a PR to implement the `setBufferSize()` method.  Hoping you'd be willing to merge and release this

**Comment by Julusian** [comment]
Thanks, this is published in v3.3.0
