### ISSUE TITLE
Napi error thrown after receiving after-touch

### ISSUE THREAD

**Issue by navelpluisje** [Julusian/node-midi#4]
After receiving an after touch message next error gets thrown: 
`libc++abi: terminating with uncaught exception of type Napi::Error`

This can be reproduced by cloning and running https://github.com/navelpluisje/electron-midi-starter. Let it receive an after-touch message and an error message should appear.

**Comment by aolsenjazz** [comment]
I think this might problem with your implementation; all 2-byte messages sent to your application (programchange, etc) cause it to crash.

For others verifying before trying this library, I tested virtual ins, out, as well as hardware ins, out receiving/sending aftertouch messages. All successful. It seems to me that this issue can be closed as unrelated.

Thanks @Julusian for your work on this!

**Comment by aolsenjazz** [comment]
Looking back at this, I see you (@Julusian) define a MidiMessage as `[number, number, number]`. It would probably be helpful to change this to number[] to reinforce that length isn't guaranteed. Will open a PR

**Comment by aolsenjazz** [comment]
Opened #6

**Comment by navelpluisje** [comment]
Rechecked, was indeed an implementation issue
